[project]
name = "pipeline-builder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "oracledb>=2.5.1",
    "paramiko>=3.5.1",
    "psycopg>=3.2.5",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
]
